Feature/Docker network
othercodes/sparring-storage pull request #25
Opened 2022-09-22 09:44 UTC by sergiopalacio

2022-09-22 11:44 UTC, othercodes requested changes

2022-09-22 11:44 UTC, othercodes commented on .env.example
> -APP_KEY=
This is required? is the example file

2022-09-24 15:31 UTC, othercodes requested changes

2022-09-24 15:31 UTC, othercodes commented on .env.example
> +APP_KEY=base64:eQpZcfvY9Fv/sKi0GFs2VZsCAOT8mXO22NwzJoLhL9M=
Is this required?? is an example file...

2022-09-27 16:15 UTC, othercodes commented on .env.example
> +APP_KEY=base64:eQpZcfvY9Fv/sKi0GFs2VZsCAOT8mXO22NwzJoLhL9M=
Any update on this?

2022-09-28 12:58 UTC, sergiopalacio commented on .env.example
> +APP_KEY=base64:eQpZcfvY9Fv/sKi0GFs2VZsCAOT8mXO22NwzJoLhL9M=
Hi I missed that it should not be there

2022-09-28 13:59 UTC, othercodes approved these changes

2022-09-28 13:59 UTC, merged